name: Testig
favicon: null
layout_spectrum: 0.6721587972715497
typography_spectrum: 0.7852
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.18328420701436698
  lightness: 0.007283425889909267
  saturation: 0.05008614435791969
  rhythmicContrast: 0.10192821780219674
purpose: []
